### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by Czino** [bitcoinjs/regtest-server#11]
I have come across this issue that many integration tests in the bitcoinjs-lib repo are failing.

Receiving `Bad Request` for many of them

I am running the docker instance as `docker run -d -p 8080:8080 regtest-server`

And then tested individual endpoints.

Endpoints under /1/b/ seem to be working
```
$ curl --location --request GET 'http://localhost:8080/1/b/best'
0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206
```

but /1/r/generate and /1/r/faucet don't
```
curl -s -w '%{http_code}\n' --location --request POST 'http://localhost:8080/1/r/generate?count=1&key=satoshi'
401
```

```
curl -s -w '%{http_code}\n' --location --request POST 'http://localhost:8080/1/r/faucet?address=bcrt1qzg8ylgwet75ldf6crl3wyem32qstctml63chnd&key=satoshi&value=100000
400
```

**Comment by daGoodenough** [comment]
I'm having the same issues. @Czino did you ever figure this one out?

**Comment by Czino** [comment]
Hey @daGoodenough, I wish I would have followed up on this with a clear answer immediately 

I am running actually this comment now which seem to make it all work
`docker run -d -p 8080:8080 junderw/bitcoinjs-regtest-server`
