### ISSUE TITLE
npm install fails (on macos)

### ISSUE THREAD

**Issue by landabaso** [bitcoinjs/regtest-server#12]
It's not a bug within regtest-server. It looks like it's related to one of the dependencies of the package:

```
npm ERR! code 1
npm ERR! path /Users/lbo/bitcoin/regtest-server/regtest-server/node_modules/leveldown
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
```

Anyone with the same problem?

I cannot use the docker image since I want to run regtest-server with my own instance of bitcoind.

EDIT:

I edited package.json and updated leveldown to:

`    "leveldown": "^6.1.1",`

This let me install the package. However I'm not sure about possible consequences (being a major version change).

EDIT2:

I confirm "leveldown": "^6.1.1" loads the server and works fine paired with regtest-client. I've been doing basic tests calling `regtestUtils.faucet` and so far so good. New blocks are mined and apparently everything is ok.

I believe it's safe to update package.json. I won't be doing a pull request since I might break things. @junderw may want to take a look.

**Comment by a-straus** [comment]
Adding here:

I had to use the following to start it:
`"start": "KEYDB=regtest-data/KEYS INDEXDB=regtest-data/db PORT=8080 ZMQ=tcp://127.0.0.1:30001 RPC=http://localhost:18442 RPCCOOKIE=/Users/traus/dev/yacht/btc/regtest-data/regtest/.cookie node index.js",`

Then have to make the regtest-data directory and then `echo "satoshi" > regtest-data/KEYS`

**Comment by tothstevee** [comment]
Is there any update about it?

**Comment by junderw** [comment]
Nope. There are some workarounds above.

**Comment by tothstevee** [comment]
But my problem is not in the start case i have issue with the npm install command

**Comment by landabaso** [comment]
Fixed in https://github.com/bitcoinjs/regtest-server/pull/13
